<<: &shared
  language_name: Ojibway
mappings:
  - display_name: Ojibway to IPA
    in_lang: oji
    out_lang: oji-ipa
    authors:
      - Eric Joanis
    type: mapping
    mapping: oji_to_ipa.csv
    as_is: true
    case_sensitive: false
    norm_form: 'NFC'
    <<: *shared
