language_name: generated
mappings:
  - display_name: Atikamekw IPA to English IPA
    in_lang: atj-ipa
    language_name: Atikamekw
    mapping: atj-ipa_to_eng-ipa.json
    out_lang: eng-ipa
  - author: Generated 2019-09-17 16:27:11.132510
    display_name: Gitksan IPA to English IPA
    in_lang: git-ipa
    language_name: Gitksan
    mapping: git-ipa_to_eng-ipa.json
    out_lang: eng-ipa
