<<: &shared
  language_name: Tlingit
mappings:
  - display_name: Tlingit to IPA
    in_lang: tli
    out_lang: tli-ipa
    authors:
      - Shankhalika Srikanth
    type: mapping
    mapping: tli_to_ipa.csv
    prevent_feeding: true
    as_is: true
    case_sensitive: false
    norm_form: NFC
    <<: *shared
