<<: &shared
  language_name: Raga
mappings:
  - display_name: Raga to IPA
    mapping: lml_to_ipa.csv
    in_lang: lml
    out_lang: lml-ipa
    case_sensitive: false
    norm_form: NFD
    as_is: true
    abbreviations: abbreviations.csv
    authors:
      - Fineen Davis
    <<: *shared
