<<: &shared
  language_name: Innu-Aimun
mappings:
  - display_name: Innu-Aimun Normalization
    in_lang: moe
    out_lang: moe-equiv
    type: mapping
    authors:
      - Delasie Torkornoo
    mapping: moe_equiv.json
    <<: *shared