# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package
on:
  release:
    types: [created]
  push:
    branches: [ release ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
    - name: Tag the repo
      run: |
        VERSION=`ls dist/g2p-*.tar.gz | sed -e 's/.*g2p-//' -e 's/.tar.gz.*//'`
        git config --global user.email hello@aidanpine.ca
        git config --global user.name "Aidan Pine via GitHub Actions"
        git tag -a -m"Release version $VERSION" v$VERSION
        git push origin v$VERSION
    - name: trigger convertextract build
      run: |
        curl --location --request POST 'https://api.github.com/repos/roedoejet/convertextract/dispatches' \
        --header 'Accept: application/vnd.github.everest-preview+json' \
        --header 'Content-Type: application/json' \
        --header 'Authorization: Bearer ${{ secrets.G2P_PAT }}' \
        --header 'Content-Type: text/plain' \
        --data-raw '{
          "event_type": "g2p-published",
          "client_payload": {}
        }'
